"""empty message

Revision ID: c1b659e6d6a2
Revises: 5ae3939b8c4b
Create Date: 2023-09-01 11:33:14.943322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b659e6d6a2'
down_revision = '5ae3939b8c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_article',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'image')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images_article')
    # ### end Alembic commands ###
